image: alpine:latest

pages:
  script:
    - apk add --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ zola
    - zola build
  
  artifacts:
    paths:
      - public
  
  only:
    - master