# The URL the site will be built for
base_url = "https://ben-website.gitlab.io"

title = "Site Title Here"

description = "Short description here."

compile_sass = true

build_search_index = true

taxonomies = [
    { name = "tags" },
]

external_links_target_blank = true
minify_html = true

[markdown]
highlight_code = false
smart_punctuation = true

[extra]
default_keywords = [
    "Tabletop", "Role playing game", "RPG", "TTRPG", "Dice"
]
author = "Ben Lickerman"