name = "Complex"
die = 6
resultname = "Do"

results = [
    { on = 1, result = "Brief description" },
    { on = 2, result = "Another description" },
    { on = 3, result = "Third description" },
    { on = 4, result = "Nothing, actually" },
    { on = { start = 5, end = 6 }, result = "Multiple cases" },
]
